# Generated by Django 4.2.1 on 2024-09-17 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_store', '0002_initial'),
        ('chatbots', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='data_sources',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_store.datastore'),
        ),
    ]
