# Generated by Django 4.2.1 on 2024-09-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='industry',
            field=models.CharField(default='', max_length=100),
        ),
    ]
