# Generated by Django 4.2.1 on 2024-09-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0005_alter_chatbot_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
