# Generated by Django 4.2.1 on 2024-09-17 17:00

import company.models
import data_store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField(verbose_name='answer')),
                ('data_source', models.CharField(max_length=500, verbose_name=data_store.models.DataStore)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_website', models.CharField(max_length=500, verbose_name=company.models.Company)),
            ],
        ),
    ]
