# Generated by Django 4.2.1 on 2024-09-14 09:46

import company.models
import data_store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='company_website',
            field=models.CharField(max_length=500, verbose_name=company.models.Company),
        ),
        migrations.AlterField(
            model_name='chat',
            name='data_source',
            field=models.CharField(max_length=500, verbose_name=data_store.models.DataStore),
        ),
    ]
