# Generated by Django 4.2.1 on 2024-11-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_subscription', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_social_media_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_chatbots',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_plan_name',
            field=models.CharField(default=False),
        ),
    ]
