# Generated by Django 4.2.1 on 2024-09-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('number_of_chatbots', models.PositiveIntegerField(default=0)),
                ('number_of_queries', models.PositiveIntegerField(default=0)),
                ('number_of_users', models.PositiveIntegerField(default=0)),
                ('website', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
