# Generated by Django 4.2.1 on 2024-10-17 16:37

from django.db import migrations, models
import pgvector.django.indexes
import pgvector.django.vector
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_store', '0001_vector_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('created_by', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('tokens', models.PositiveIntegerField()),
                ('content', models.TextField(verbose_name='Content')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, help_text='Vector embeddings', null=True)),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='clip_l14_vectors_index', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
