# Generated by Django 4.2.1 on 2024-09-12 20:10

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.vector


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('data_store', '0001_vector_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company_website', models.CharField(max_length=100)),
                ('tokens', models.PositiveIntegerField()),
                ('content', models.TextField(verbose_name='Content')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, help_text='Vector embeddings', null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
