# Generated by Django 4.2.1 on 2024-08-24 09:46

from django.db import migrations
import pgvector.django.indexes


class Migration(migrations.Migration):

    dependencies = [
        ('data_store', '0002_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='datastore',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='clip_l14_vectors_index', opclasses=['vector_cosine_ops']),
        ),
    ]
