# Generated by Django 4.2.1 on 2024-09-12 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.indexes


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_store', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastore',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='datastore',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='clip_l14_vectors_index', opclasses=['vector_cosine_ops']),
        ),
    ]
