# Generated by Django 4.2.1 on 2024-09-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_store', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastore',
            name='company_website',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='datastore',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
